Los tweets son cortos y concisos, luego para el sentiment analysis, podemos usar un enfoque como el spam detection con Naive Bayes con las veces que aparece una palabra, pero ya que estamos usaremos el TF-IDF que es una metrica que mide la tasa en la que aparece y pone mas valor a las palabras que no aparecen tanto

In [15]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import BernoulliNB, MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score, classification_report

In [2]:
df = pd.read_csv('tweets.csv', encoding='latin-1', header=None)

In [ ]:
df.iloc[:,0].value_counts()

Index([0, 4], dtype='int64', name=0)

In [18]:
df[[0,5]]

         0                                                  5
0        0  @switchfoot http://twitpic.com/2y1zl - Awww, t...
1        0  is upset that he can't update his Facebook by ...
2        0  @Kenichan I dived many times for the ball. Man...
3        0    my whole body feels itchy and like its on fire
4        0  @nationwideclass no, it's not behaving at all....
...     ..                                                ...
1599995  4  Just woke up. Having no school is the best fee...
1599996  4  TheWDB.com - Very cool to hear old Walt interv...
1599997  4  Are you ready for your MoJo Makeover? Ask me f...
1599998  4  Happy 38th Birthday to my boo of alll time!!! ...
1599999  4  happy #charitytuesday @theNSPCC @SparksCharity...

[1600000 rows x 2 columns]

In [3]:
df = df[[0,5]]

In [4]:
df.rename(columns={0:"polarity", 5: "text"}, inplace= True)

In [21]:
df.head()

   polarity                                               text
0         0  @switchfoot http://twitpic.com/2y1zl - Awww, t...
1         0  is upset that he can't update his Facebook by ...
2         0  @Kenichan I dived many times for the ball. Man...
3         0    my whole body feels itchy and like its on fire
4         0  @nationwideclass no, it's not behaving at all....

In [5]:
# 0 means negative, and 1 positive (change 4 with 1)
df['polarity'] = df['polarity'].map({0:0,4:1})
print(df['polarity'].value_counts())

polarity
0    800000
1    800000
Name: count, dtype: int64

In [6]:
def clean_text(text):
    return text.lower()

print(clean_text("AA"))

aa

In [7]:
df['clean_text'] = df['text'].apply(clean_text)
print(df[['text', 'clean_text']].head())

                                                text  \
0  @switchfoot http://twitpic.com/2y1zl - Awww, t...
1  is upset that he can't update his Facebook by ...
2  @Kenichan I dived many times for the ball. Man...
3    my whole body feels itchy and like its on fire
4  @nationwideclass no, it's not behaving at all....

                                          clean_text
0  @switchfoot http://twitpic.com/2y1zl - awww, t...
1  is upset that he can't update his facebook by ...
2  @kenichan i dived many times for the ball. man...
3    my whole body feels itchy and like its on fire
4  @nationwideclass no, it's not behaving at all....

In [8]:
#Subdividimos los datos en training y test
X_train, X_test, y_train, y_test = train_test_split(df['clean_text'], df['polarity'], test_size=0.2, random_state=42)

print("Train size:", len(X_train))
print("Test size:", len(X_test))

Train size: 1280000
Test size: 320000

In [9]:
#Empezamos la vectorizacion del TF-IDF y hacemos ngramas de 1 o 2 palabras.
vectorizer = TfidfVectorizer(max_features=5000, ngram_range=(1,2))

X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

print("TF-IDF shape (train):", X_train_tfidf.shape)
print("TF-IDF shape (test):", X_test_tfidf.shape)

TF-IDF shape (train): (1280000, 5000)
TF-IDF shape (test): (320000, 5000)

In [10]:
#Empezamos con Bernouilli NB, para nuestros datos.
bnb = BernoulliNB()
bnb.fit(X_train_tfidf, y_train)

bnb_pred = bnb.predict(X_test_tfidf)

print("Bernoulli Naive Bayes Accuracy:", accuracy_score(y_test, bnb_pred))
print("\nBernoulliNB Classification Report:\n", classification_report(y_test, bnb_pred))

Bernoulli Naive Bayes Accuracy: 0.766478125

BernoulliNB Classification Report:
               precision    recall  f1-score   support

           0       0.77      0.75      0.76    159494
           1       0.76      0.78      0.77    160506

    accuracy                           0.77    320000
   macro avg       0.77      0.77      0.77    320000
weighted avg       0.77      0.77      0.77    320000

No tiene mucho accuracy pero esta decente, ahora provaremos un LinearSVC.

In [11]:
svm = LinearSVC(max_iter=1000)
svm.fit(X_train_tfidf, y_train)

svm_pred = svm.predict(X_test_tfidf)

print("SVM Accuracy:", accuracy_score(y_test, svm_pred))
print("\nSVM Classification Report:\n", classification_report(y_test, svm_pred))

SVM Accuracy: 0.79528125

SVM Classification Report:
               precision    recall  f1-score   support

           0       0.80      0.78      0.79    159494
           1       0.79      0.81      0.80    160506

    accuracy                           0.80    320000
   macro avg       0.80      0.80      0.80    320000
weighted avg       0.80      0.80      0.80    320000

Ahora probemos una regresion logistica

In [12]:
logreg = LogisticRegression(max_iter=100)
logreg.fit(X_train_tfidf, y_train)

logreg_pred = logreg.predict(X_test_tfidf)

print("Logistic Regression Accuracy:", accuracy_score(y_test, logreg_pred))
print("\nLogistic Regression Classification Report:\n", classification_report(y_test, logreg_pred))

Logistic Regression Accuracy: 0.79539375

Logistic Regression Classification Report:
               precision    recall  f1-score   support

           0       0.80      0.78      0.79    159494
           1       0.79      0.81      0.80    160506

    accuracy                           0.80    320000
   macro avg       0.80      0.80      0.80    320000
weighted avg       0.80      0.80      0.80    320000

Ahora en vez de bernouilli hagamos multinomial por probar

In [16]:
mnb = MultinomialNB()
mnb.fit(X_train_tfidf, y_train)

mnb_pred = mnb.predict(X_test_tfidf)

print("Multinomial Naive Bayes Accuracy:", accuracy_score(y_test, mnb_pred))
print("\MultinomialNB Classification Report:\n", classification_report(y_test, mnb_pred))

Multinomial Naive Bayes Accuracy: 0.772175
\MultinomialNB Classification Report:
               precision    recall  f1-score   support

           0       0.76      0.79      0.78    159494
           1       0.78      0.76      0.77    160506

    accuracy                           0.77    320000
   macro avg       0.77      0.77      0.77    320000
weighted avg       0.77      0.77      0.77    320000

Veremos las predicciones

In [17]:
sample_tweets = ["I love this!", "I hate that!", "It was okay, not great."]
sample_vec = vectorizer.transform(sample_tweets)

print("\nSample Predictions:")
print("BernoulliNB:", bnb.predict(sample_vec))
print("MultinomialNB:", mnb.predict(sample_vec))
print("SVM:", svm.predict(sample_vec))
print("Logistic Regression:", logreg.predict(sample_vec))

Sample Predictions:
BernoulliNB: [1 0 1]
MultinomialNB: [1 0 1]
SVM: [1 0 1]
Logistic Regression: [1 0 1]